name: Deploy documentation

# GitHub events that triggers the workflow:
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Installing the Documentation requirements
        run: |
            python -m pip install --upgrade pip
            pip install .[docs]
      
      - name: Installing the library
        run: |
          python setup.py install

      - name: Run Sphinx build action 
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - uses: actions/upload-artifact@v4
        with:
          name: DocumentationHTML
          path: docs/_build/html/
